[gcp_service_account]
json = '''
{
  "type": "service_account",
  "project_id": "streamlit-userauth",
  "private_key_id": "d2f6ec3db520ec64f35ab7224b31d6d935a31ff3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDqs7AeZPqMvA3i\n...rest of key...\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-auth@streamlit-userauth.iam.gserviceaccount.com",
  "client_id": "113516096772281376605",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-auth%40streamlit-userauth.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''

[omdb]
api_key = "c2b7a95e"
