[gcp_service_account]
json = '''

  "{
  "type": "service_account",
  "project_id": "streamlit-userauth",
  "private_key_id": "d2f6ec3db520ec64f35ab7224b31d6d935a31ff3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDqs7AeZPqMvA3i\na5zwKv6KawFV9v5cVbE16ecrB52kXrYlSR+W10x7xtWnVccXCpswq+kAeCF4d7Ym\nus3Qu6Q0xCuDklY81uMg7QsOIG/ClJtYCJE1ecYawEdOJwk5Lju5hK8d3unzM2KD\npfjlYRQsPE/bbln36vjCePV6AAJa2uQovpysX+KgUapXTopNCekaFSPeYDrTR7mL\nqUITzp90LeB9X2k/xv9+BMUe+unt7MA2NA95PRp4G+U7J9KnSGFMQcw2Wj82ngbn\ntgCl1Q7aoxmteRK2E6tHvmpwBvUTSj+VZ6CTyjhsBFSFmYgSnNVpCLLqP9Zwsqh1\n2wFjNHcbAgMBAAECggEACIqLgT+pgo+hbbj+2Bqocr8cKFW5wgB4V37wo7c+PGoZ\n9NdpZ+Lj7Kk6w0Ey4prHNQk8jIDSrwCkR1qK/OqnOihdcQdVThd/4oXd3iC+EHW6\nBYUiS7DnzbdroON4yXTuRX0Xpl2jY+9dyW6z1R0oT8fOHC0y5vvNG76tKEhxzX6R\n7kfosepEySeQDGWcnSg0h9tRaihAbtCqJq+3sp58RlKUuLFhVT7343yAN8iXZ9vv\nDASXEk5F1AmFjxKUj3Cf0u7ADpTGxENuUX3u5G3p8TtYvHWTDgoFUe2qetvrsWOT\nv0LldpuOAi3oV1ElP6T77lww2gseQSwaonpq43uFoQKBgQD+6KsuQU8sp2iu2M+d\nS+6EiVQG8hFv8skqMmnZ1pESFFoI0lxBF3sBwWzJ3uTi/1uSBnWaLl0GbTDwTOgp\nlUM0/iAfW4t32EM4hhsA3Cy9X8QiWrymnhe94sNkPkvGHLel6DoHHkzJ54bK3of9\nBG5YHazv9L52SfXc1VTvWQJi6wKBgQDrtOBXXAq7Zq3RUJeBQyOVgTTmqqcs3nHK\nWLmfltj9BqVA1FOMxdYDRPpVmRbdjwAR9kABRZQtIFkFZZfS7grVaMwFX2Mwcp7L\ntMPagLBUJdQg4jaEZLjo/8NFroWQEgWmyfucFpoGUkPy7TcM9NMw1UYp+la7CPds\nJDikB5NQkQKBgQCXLr1f+KIRlNR0ZuhznTZAawZn/Ce1YqRGn5HB/g0aUPG5K7JF\ndLyipOp1q/nKW7MenzAemoLXrekJjENhbkJm6pV4o53LHXt4yai4UN1ED8lOqswa\ncccY+qXyDTR5skyFXH8V+7WFRgjexy6WNIuRPUB1LI3NsD3elLQEJKFSswKBgBcB\nz8gXLuD988dzo2Y1pHqKYxyE2c6SY+8JXA0Mz19bT7QVRZZ/FRW6nOjQCaBUvgAC\n1lqJbR4+gxH4yaoIHDyafxejKO5oscFWgquIVi3Qh3UyP3oKztXHaUsa7uSSLcUL\nAClLN3uYehNzPiVgnGCu4KtmSSL2jBgdLP4t0x5RAoGAIIvRMAlaCjBfnpPIxFCl\nPMv+dumkz7a2MyqEjC9vwOI4hzOix0HP1c1vf03J5Q5EZnHnAOcxhzj9wuoIfx0y\nup4EMApZ/xJoN4roJbF9Z7rn2k/cOo7vm07xVyGadxNpWvzbWNcuRcXFV8npt3I1\nQNxWt8+OffMAWtl9paCT7Z0=\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-auth@streamlit-userauth.iam.gserviceaccount.com",
  "client_id": "113516096772281376605",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-auth%40streamlit-userauth.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

'''

[omdb]
api_key = "c2b7a95e"
